"""Login auto-start via a systemd --user service.

Spitch's daemon is a long-lived per-user process; the natural place
for it to live across reboots is a systemd user unit. This module
hides the systemctl invocations behind small functions:

  * :func:`is_supported` — does this system actually have ``systemctl``
    + a running ``--user`` instance?
  * :func:`is_enabled` — is the spitch unit currently enabled?
  * :func:`is_active` — is the unit currently running?
  * :func:`enable` / :func:`disable` — flip autostart.
  * :func:`restart` — bounce the daemon so config changes take effect
    (console Settings tab). Prefers ``systemctl --user restart``;
    otherwise SIGTERM ``python -m spitch`` (not console/cli/config)
    and respawn the launcher.

The unit file lives at ``~/.config/systemd/user/spitch.service`` and
is owned and managed by Spitch. ``enable`` writes / overwrites it
(idempotent), runs ``daemon-reload`` + ``enable --now``, and reports
status via a ``(ok, message)`` tuple. ``disable`` runs the reverse
and removes the file.

The unit launches the user's ``~/.local/bin/spitch-daemon`` launcher
script that the install.sh generates — that script sets PYTHONPATH +
log redirection, so the systemd unit just exec's it.

Caveats — surfaced to the UI as needed:

* The user must be in the ``input`` group for /dev/input/event*
  reads. Auto-start does not fix this; spitch-daemon will exit 3
  ("no readable keyboard devices") if input group is missing. We
  warn in the UI when enabling auto-start.
* On systems with a graphical session bus but no systemd-logind
  user instance (e.g. some non-systemd distros), ``systemctl --user``
  will fail. :func:`is_supported` returns False there, and the UI
  hides the checkbox.
"""

from __future__ import annotations

import os
import signal
import shutil
import subprocess
import time
from pathlib import Path
from typing import Sequence, Tuple

UNIT_NAME = "spitch.service"

# ``python -m <mod>`` modules that are the daemon itself. Console / cli /
# config_dialog are ``spitch.ui.*`` / ``spitch.cli`` and must survive a
# restart triggered from those processes.
_DAEMON_MODULES = frozenset({"spitch", "spitch.daemon", "spitch.__main__"})


def unit_dir() -> Path:
    """``~/.config/systemd/user`` honoring ``$XDG_CONFIG_HOME``."""
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "systemd" / "user"


def unit_path() -> Path:
    return unit_dir() / UNIT_NAME


def daemon_launcher_path() -> Path:
    """Path the unit's ExecStart= points at — the script
    install.sh writes."""
    return Path.home() / ".local" / "bin" / "spitch-daemon"


def render_unit() -> str:
    """Build the unit-file content. Pure function — easy to unit-test
    without touching the filesystem."""
    return (
        "# Auto-generated by Spitch. Edit via the console settings tab,\n"
        "# or remove with `systemctl --user disable --now spitch.service`.\n"
        "[Unit]\n"
        "Description=Spitch voice-input daemon\n"
        "After=graphical-session.target\n"
        "PartOf=graphical-session.target\n"
        "\n"
        "[Service]\n"
        f"ExecStart={daemon_launcher_path()}\n"
        "Restart=on-failure\n"
        "RestartSec=2\n"
        # Exit 2 = incomplete / not verified (user must re-probe after
        # switching provider). Exit 3 = no readable /dev/input devices.
        # Restarting those every 2s just floods daemon.log.
        "RestartPreventExitStatus=2 3\n"
        # Bound stop so a wedged clean-exit path cannot strand the unit
        # in stop-sigterm for the manager default (often 90s). mixed:
        # SIGTERM the main process first; after the timeout SIGKILL the
        # whole cgroup (arecord children, any non-detached helpers).
        "TimeoutStopSec=8\n"
        "KillMode=mixed\n"
        "\n"
        "[Install]\n"
        "WantedBy=graphical-session.target\n"
    )


def is_supported() -> bool:
    """``systemctl`` is on PATH AND a user instance is reachable.

    Returns False on non-systemd distros and on hosts where the
    daemon is being driven outside any logind session. Used by the
    UI to hide the auto-start checkbox when it can't possibly work.
    """
    if shutil.which("systemctl") is None:
        return False
    try:
        r = subprocess.run(
            ["systemctl", "--user", "is-system-running"],
            capture_output=True, timeout=2.0, text=True,
        )
        # Even "degraded" / "starting" / "running" mean a user
        # manager is up. Only "offline" / connection refused means
        # we can't talk to it. Treat any non-zero exit other than
        # the well-known string outputs as unsupported.
        out = (r.stdout or "").strip().lower()
        if out in ("running", "degraded", "starting", "maintenance"):
            return True
        # "is-system-running" returning empty/offline => no user bus.
        if not out:
            return False
        # Fall back: try a cheap query — if it succeeds we're talking.
        r2 = subprocess.run(
            ["systemctl", "--user", "list-unit-files", "--type=service",
             "--no-legend", "--no-pager"],
            capture_output=True, timeout=2.0,
        )
        return r2.returncode == 0
    except (subprocess.TimeoutExpired, OSError):
        return False


def is_enabled() -> bool:
    """Is the spitch user unit currently enabled?

    Returns False when the unit file is missing or systemctl reports
    "disabled" / "static" / "not-found" / etc.
    """
    if not unit_path().exists():
        return False
    if shutil.which("systemctl") is None:
        return False
    try:
        r = subprocess.run(
            ["systemctl", "--user", "is-enabled", UNIT_NAME],
            capture_output=True, timeout=2.0, text=True,
        )
        # systemctl prints e.g. "enabled\n" / "disabled\n" / "static\n"
        # and exits 0 only for "enabled" / "alias" / "static" / "linked".
        # We only care about "enabled" specifically.
        return (r.stdout or "").strip() == "enabled"
    except (subprocess.TimeoutExpired, OSError):
        return False


def is_active() -> bool:
    """Is the systemd user unit currently running?

    False when systemctl is missing, the unit is inactive/failed, or
    the query times out. Does not look at a manually-launched daemon.
    """
    if shutil.which("systemctl") is None:
        return False
    try:
        r = subprocess.run(
            ["systemctl", "--user", "is-active", UNIT_NAME],
            capture_output=True, timeout=2.0, text=True,
        )
        return (r.stdout or "").strip() == "active"
    except (subprocess.TimeoutExpired, OSError):
        return False


def is_daemon_argv(argv: Sequence[str]) -> bool:
    """True if ``argv`` is the Spitch daemon, not console / cli / config.

    Matches ``python -m spitch`` (and ``spitch.daemon`` /
    ``spitch.__main__``). Rejects ``python -m spitch.ui.console`` so a
    restart from the Settings tab cannot kill the window that issued it.
    """
    parts = [p for p in argv if p]
    for i, part in enumerate(parts):
        if part == "-m" and i + 1 < len(parts):
            return parts[i + 1] in _DAEMON_MODULES
    return False


def _daemon_pids() -> list[int]:
    """PIDs whose cmdline is the daemon. Skips our own process."""
    my_pid = os.getpid()
    found: list[int] = []
    proc = Path("/proc")
    try:
        entries = list(proc.iterdir())
    except OSError:
        return found
    for entry in entries:
        name = entry.name
        if not name.isdigit():
            continue
        pid = int(name)
        if pid == my_pid:
            continue
        try:
            raw = (entry / "cmdline").read_bytes()
        except OSError:
            continue
        argv = [p.decode("utf-8", "replace") for p in raw.split(b"\0") if p]
        if is_daemon_argv(argv):
            found.append(pid)
    return found


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def _stop_loose_daemons(*, timeout: float = 6.0) -> None:
    """SIGTERM (then SIGKILL) any non-systemd ``python -m spitch``.

    Timeout matches the daemon's 5s shutdown watchdog plus slack.
    """
    pids = _daemon_pids()
    for pid in pids:
        try:
            os.kill(pid, signal.SIGTERM)
        except OSError:
            pass
    deadline = time.time() + timeout
    remaining = set(pids)
    while remaining and time.time() < deadline:
        remaining = {pid for pid in remaining if _pid_alive(pid)}
        if remaining:
            time.sleep(0.1)
    for pid in remaining:
        try:
            os.kill(pid, signal.SIGKILL)
        except OSError:
            pass


def _spawn_launcher() -> Tuple[bool, str]:
    launcher = daemon_launcher_path()
    if not launcher.exists():
        return False, (
            f"找不到 daemon launcher：{launcher}。请先跑 ./scripts/install.sh"
        )
    try:
        subprocess.Popen(
            [str(launcher)],
            start_new_session=True,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except OSError as exc:
        return False, f"启动失败：{exc}"
    return True, "daemon 已重新启动"


def restart() -> Tuple[bool, str]:
    """Bounce the daemon so a saved config takes effect.

    When the user unit file exists and ``systemctl --user`` works:
    rewrite the unit (picks up TimeoutStopSec / KillMode changes),
    ``daemon-reload``, then ``restart``. If the unit is not active,
    any leftover manual ``python -m spitch`` is stopped first so we
    do not end up with two daemons.

    Otherwise stop leftover daemon PIDs and spawn the install.sh
    launcher in a new session (console stays up).
    """
    if is_supported() and unit_path().exists():
        if not is_active():
            _stop_loose_daemons()
        try:
            unit_path().write_text(render_unit(), encoding="utf-8")
        except OSError as exc:
            return False, f"更新 unit 文件失败：{exc}"
        try:
            r = subprocess.run(
                ["systemctl", "--user", "daemon-reload"],
                capture_output=True, timeout=5.0, text=True,
            )
            if r.returncode != 0:
                return False, f"daemon-reload 失败：{(r.stderr or '').strip()}"
            r = subprocess.run(
                ["systemctl", "--user", "restart", UNIT_NAME],
                capture_output=True, timeout=20.0, text=True,
            )
            if r.returncode != 0:
                return False, f"restart 失败：{(r.stderr or '').strip()}"
            return True, "daemon 已重启（systemd --user）"
        except subprocess.TimeoutExpired:
            return False, "systemctl restart 超时"
        except OSError as exc:
            return False, f"systemctl 调用失败：{exc}"

    _stop_loose_daemons()
    return _spawn_launcher()


def restart_if_running() -> Tuple[bool, str]:
    """Reload saved configuration without unexpectedly starting Spitch.

    ``spitch-config`` uses this after a verified save. A running systemd
    service or loose ``python -m spitch`` process is restarted; when no
    daemon is running, the next normal start will read the new config.
    """
    if is_active() or _daemon_pids():
        return restart()
    return True, "配置已保存；daemon 未运行，将在下次启动时生效"


def enable() -> Tuple[bool, str]:
    """Write the unit, daemon-reload, enable --now. Idempotent —
    safe to call when the service is already enabled."""
    if shutil.which("systemctl") is None:
        return False, "systemctl 不在 PATH 上（这台机器不支持 systemd --user）"
    launcher = daemon_launcher_path()
    if not launcher.exists():
        return False, (
            f"找不到 daemon launcher：{launcher}。请先跑 ./scripts/install.sh"
        )
    try:
        unit_dir().mkdir(parents=True, exist_ok=True)
        unit_path().write_text(render_unit(), encoding="utf-8")
        # daemon-reload picks up the new file
        r = subprocess.run(
            ["systemctl", "--user", "daemon-reload"],
            capture_output=True, timeout=5.0, text=True,
        )
        if r.returncode != 0:
            return False, f"daemon-reload 失败：{(r.stderr or '').strip()}"
        # enable --now: register at boot AND start it now
        r = subprocess.run(
            ["systemctl", "--user", "enable", "--now", UNIT_NAME],
            capture_output=True, timeout=10.0, text=True,
        )
        if r.returncode != 0:
            return False, (
                f"enable 失败：{(r.stderr or '').strip()}。"
                "如果你已经有一个 daemon 在跑，先把它 kill 掉再试。"
            )
        return True, "已启用：下次登录会自动启动 daemon"
    except subprocess.TimeoutExpired:
        return False, "systemctl 调用超时"
    except OSError as exc:
        return False, f"写入 unit 文件失败：{exc}"


def disable() -> Tuple[bool, str]:
    """disable --now and remove the unit file. Idempotent."""
    if shutil.which("systemctl") is None:
        return False, "systemctl 不在 PATH 上"
    try:
        # disable --now: stop running instance + un-register from boot
        r = subprocess.run(
            ["systemctl", "--user", "disable", "--now", UNIT_NAME],
            capture_output=True, timeout=10.0, text=True,
        )
        # disable can return non-zero if unit was never enabled — that's
        # OK for the "make sure it's off" semantics we want.
        # Then remove the file regardless.
        try:
            unit_path().unlink()
        except FileNotFoundError:
            pass
        # Re-load so systemd forgets the file path.
        subprocess.run(
            ["systemctl", "--user", "daemon-reload"],
            capture_output=True, timeout=5.0,
        )
        if r.returncode != 0 and "not loaded" not in (r.stderr or "").lower():
            # genuine failure (not just "already gone")
            return False, f"disable 部分失败：{(r.stderr or '').strip()}"
        return True, "已关闭：下次登录不会自动启动"
    except subprocess.TimeoutExpired:
        return False, "systemctl 调用超时"
    except OSError as exc:
        return False, f"删除 unit 文件失败：{exc}"
